// Estructuras de Datos.cpp : Este archivo contiene la función "main". La ejecución del programa comienza y termina ahí.
//

// #include <iostream>

// EN ESTA CLASE DEL MAIN UTILIZAREMOS ESPACIO DE NOMBRES.

// using namespace std;

// VAMOS A TRABAJAR CON ALGUNAS DE SUS FUNCIONES EN ESTA SECCIÓN DEL MENÚ...

int funcion1(int *a)
{
    // PRIMERA FUNCIÓN QUE UTILIZA COMO VARIABLE UNA INCÓGNITA YA DECLARADA CON UN PUNTERO...

    (*a)--; // DISMINUYE EL VALOR DE SU INCÓGNITA.
    return (*a); // RETORNA EL VALOR DISMINUIDO DE SU INCÓGNITA.
}

int funcion2(int a)
{
    // SEGUNDA FUNCIÓN QUE UTILIZA COMO VARIABLE UNA INCÓGNITA YA DECLARADA NORMALMENTE...

    a--; // DISMINUYE EL VALOR DE SU INCÓGNITA.
    return a; // RETORNA EL VALOR DISMINUIDO DE SU INCÓGNITA.
}

int main()
{
    // ESTA ES LA CLASE DEL MAIN POR DEFECTO.

    // REALIZAREMOS OPERACIONES ALGEBRAICAS EN ESTE MÉTODO.

    int x = 4; // "x" ES IGUAL A 4.
    /*x++; // INCREMENTA SU VALOR AL PRINCIPIO DE ESTA VARIABLE YA DECLARADA.
    int y = 8; // "y" ES IGUAL A 8.

    // PARA PRACTICAR UN POCO CON ESTE LENGUAJE DE PROGRAMACIÓN, VAMOS A CREAR UN CICLO "for".

    for (int i = 0; i < 10; i++) // LOS NÚMEROS YA DECLARADOS EN ESTA ITERACIÓN ESTARÁN ENTRE EL 0 Y EL 9.
    {
        y++; // INCREMENTA SU VAOR EN "y".
    }
    */

    // COMO TODO LO DEMÁS YA ESTÁ COMENTADO, VAMOS A EJECUTAR LOS SIGUIENTES MÉTODOS AQUÍ, UTILIZANDO UNA VARIABLE DECLARADA AHÍ ARRIBA...

    funcion1(&x); // CON ESTE PUNTERO NO DEVUELVE NINGÚN VALOR EN X, YA QUE DICHO PUNTERO ASOCIADO ES UNA CONSTANTE.
    funcion2(x); // ÉSTE SÍ DEVUELVE UN VALOR.
};

